### ISSUE TITLE
[BUG] <title>卡在Triton Inference Server部分，显示显卡型号后卡住。

### ISSUE THREAD

**Issue by wj920291253** [netease-youdao/QAnything#221]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

执行bash ./run.sh -c local -i 0 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything后，卡在Triton Inference Server，显示显卡型号后，卡住。

### 期望行为 | Expected Behavior

bash ./run.sh -c local -i 0 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
====================================================
******************** 重要提示 ********************
====================================================

检测到master分支有新的代码更新，如需体验最新的功能，可以手动执行 git pull 来同步最新的代码。

请输入您使用的大模型B数(示例：1.8B/3B/7B): 7B
model_size=7B
GPUID1=0, GPUID2=0, device_id=0
llm_api is set to [local]
device_id is set to [0]
runtime_backend is set to [hf]
model_name is set to [Qwen-7B-QAnything]
conv_template is set to [qwen-7b-qanything]
tensor_parallel is set to [1]
gpu_memory_utilization is set to [0.81]
Do you want to use the previous ip: 10.31.2.11? (yes/no) 是否使用上次的ip: ？(yes/no) 回车默认选yes，请输入:no
Are you running the code on a remote server or on your local machine? (remote/local) 您是在远程服务器上还是本地机器上启动代码？(remote/local) local
Running under native Linux
Stopping qanything-container-local ... 
Stopping milvus-standalone-local   ... 
Stopping milvus-minio-local        ... 
Stopping mysql-container-local     ... 
Stopping es-container-local        ... 
Stopping milvus-etcd-local         ... 
Stopping qanything-container-local ... done
Stopping milvus-standalone-local   ... done
Stopping milvus-etcd-local         ... done
Stopping milvus-minio-local        ... done
Stopping mysql-container-local     ... done
Stopping es-container-local        ... done
Removing qanything-container-local ... 
Removing milvus-standalone-local   ... 
Removing milvus-minio-local        ... 
Removing mysql-container-local     ... 
Removing es-container-local        ... 
Removing milvus-etcd-local         ... 
Removing milvus-etcd-local         ... done
Removing mysql-container-local     ... done
Removing milvus-standalone-local   ... done
Removing es-container-local        ... done
Removing milvus-minio-local        ... done
Removing qanything-container-local ... done
Removing network qanything_milvus_mysql_local
Creating network "qanything_milvus_mysql_local" with the default driver
Creating mysql-container-local ... done
Creating es-container-local      ... done
Creating milvus-minio-local    ... done
Creating milvus-etcd-local     ... done
Creating milvus-standalone-local ... done
Creating qanything-container-local ... done
Attaching to qanything-container-local
qanything-container-local | 
qanything-container-local | =============================
qanything-container-local | == Triton Inference Server ==
qanything-container-local | =============================
qanything-container-local | 
qanything-container-local | NVIDIA Release 23.05 (build 61161506)
qanything-container-local | Triton Server Version 2.34.0
qanything-container-local | 
qanything-container-local | Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local | 
qanything-container-local | Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local | 
qanything-container-local | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
qanything-container-local | By pulling and using the container, you accept the terms and conditions of this license:
qanything-container-local | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
qanything-container-local | 
qanything-container-local | llm_api is set to [local]
qanything-container-local | device_id is set to [0]
qanything-container-local | runtime_backend is set to [hf]
qanything-container-local | model_name is set to [Qwen-7B-QAnything]
qanything-container-local | conv_template is set to [qwen-7b-qanything]
qanything-container-local | tensor_parallel is set to [1]
qanything-container-local | gpu_memory_utilization is set to [0.81]
qanything-container-local | checksum e18e2231b7a37236b1ac5b3c30277b48
qanything-container-local | default_checksum e18e2231b7a37236b1ac5b3c30277b48
qanything-container-local | GPU ID: 0, 0
qanything-container-local | ������������������ NVIDIA A800 80GB PCIe ������������������������������������������������

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:535.154.05
- CUDA:12.2
- docker:24.0.7
- docker-compose:1.29。2
- NVIDIA GPU: A800 
- NVIDIA GPU Memory: 80G
```

### QAnything日志 | QAnything logs

无日志显示

### 备注 | Anything else?

重新下载最新master代码，仍提示需要更新。

**Comment by Cicinnus0407** [comment]
相同问题，显卡型号：RTX3070.
qanything-container-local |
qanything-container-local | =============================
qanything-container-local | == Triton Inference Server ==
qanything-container-local | =============================
qanything-container-local |
qanything-container-local | NVIDIA Release 23.05 (build 61161506)
qanything-container-local | Triton Server Version 2.34.0
qanything-container-local |
qanything-container-local | Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local |
qanything-container-local | Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local |
qanything-container-local | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
qanything-container-local | By pulling and using the container, you accept the terms and conditions of this license:
qanything-container-local | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
qanything-container-local |
qanything-container-local | llm_api is set to [local]
qanything-container-local | device_id is set to [0]
qanything-container-local | runtime_backend is set to [hf]
qanything-container-local | model_name is set to [Qwen-7B-QAnything]
qanything-container-local | conv_template is set to [qwen-7b-qanything]
qanything-container-local | tensor_parallel is set to [1]
qanything-container-local | gpu_memory_utilization is set to [0.81]
qanything-container-local | checksum e18e2231b7a37236b1ac5b3c30277b48
qanything-container-local | default_checksum e18e2231b7a37236b1ac5b3c30277b48
qanything-container-local | GPU ID: 0, 0
qanything-container-local | GPU1 Model: NVIDIA GeForce RTX 3070
qanything-container-local | Compute Capability: 8.6
qanything-container-local | OCR_USE_GPU=True because 8.6 >= 7.5
qanything-container-local | ====================================================
qanything-container-local | ******************** ������������ ********************
qanything-container-local | ====================================================
qanything-container-local |
qanything-container-local | ��������������������� 8192 MiB ������������1.8B������������������������������OpenAI API
qanything-container-local | ��������������������������� 3B ������������������������������������

**Comment by wj920291253** [comment]
顶顶顶，有没有大佬看下呀？

**Comment by yangy996** [comment]
有解决吗？我显示这个
![image](https://github.com/netease-youdao/QAnything/assets/15188456/827cdde0-f85b-4195-a427-d3318f40a1d3)

**Comment by wj920291253** [comment]
没解决，看来我的 ������������������就是不在支持列表中这些字咯。

**Comment by wj920291253** [comment]
解决了，根据issues #182的答案。
