### ISSUE TITLE
Can't even parse a 10M PDF successfully?

### ISSUE THREAD

**Issue by 17Reset** [netease-youdao/QAnything#79]
When I uploaded a 10+M PDF file, the parsing was not able to parse it for 30 minutes, is the parsing CPU dependent? I realized that GPU is not working while parsing.

**Comment by xixihahaliu** [comment]
When the graphics card computing power is less than 7.5, the OCR service will be deployed on the CPU by default, which may result in very slow parsing speed for large PDF files. The solution is to manually modify /path/to/QAnything/scripts/gpu_capabilities.json and set the computing power of the corresponding graphics card model to above 7.5. However, this may cause issues with memory overflow because OCR generally requires up to 2GB of video memory.

**Comment by RussellLuo** [comment]
@xixihahaliu Thanks for the explanation!

I encountered the same issue, and I found that whether to use GPU is determined by this piece of code:
https://github.com/netease-youdao/QAnything/blob/5c17a2a1955212b3e7863e3fc206549f9873e069/run.sh#L171-L175

In my case, my GPU model is `Tesla P4` and its default capability is `6.1`:

https://github.com/netease-youdao/QAnything/blob/5c17a2a1955212b3e7863e3fc206549f9873e069/scripts/gpu_capabilities.json#L60

After changing the value to `8.0`, the OCR service is successfully deployed on the GPU.
