### ISSUE TITLE
Triton启动异常

### ISSUE THREAD

**Issue by maozixi1** [netease-youdao/QAnything#9]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/netease-youdao/QAnything/assets/139109502/9e03b841-5a7e-4db0-8545-91dd16d8745c)

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- Docker Compose:
- NVIDIA GPU Memory:
```

**Comment by xixihahaliu** [comment]
Please provide detailed runtime environment information. Additionally, this may be due to low GPU computing power, resulting in slow startup of tritonserver. Please wait for 10 minutes and try again. If the issue persists, please provide the /model_repos/QAEnsemble/QAEnsemble.log file inside the container, which contains detailed logs for starting the large model service.

**Comment by maozixi1** [comment]
this is QAEnsemble.log
![image](https://github.com/netease-youdao/QAnything/assets/139109502/8f953f62-e438-4023-9fcc-2290a1a21e6a)

![image](https://github.com/netease-youdao/QAnything/assets/139109502/f3dd7362-640e-4a05-92f2-56627de0740d)

**Comment by xixihahaliu** [comment]
> this is QAEnsemble.log ![image](https://private-user-images.githubusercontent.com/139109502/295882148-8f953f62-e438-4023-9fcc-2290a1a21e6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzAyMjEsIm5iZiI6MTcwNDk2OTkyMSwicGF0aCI6Ii8xMzkxMDk1MDIvMjk1ODgyMTQ4LThmOTUzZjYyLWU0MzgtNDAyMy05ZmNjLTIyOTBhMWEyMWU2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxMDQ1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODIyYzI4NzY5Yzk0NGE3MGIyZjRmZGY1NGNmMjY0YTgxMjQwZGJjZDRkODNhMWI1N2RhOWEzZTg0N2I5ZjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nW3fpVj1ytT0BbFRD2soykAgj102uGr4mj-vIImTogU)
> 
> ![image](https://private-user-images.githubusercontent.com/139109502/295882100-f3dd7362-640e-4a05-92f2-56627de0740d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzAyMjEsIm5iZiI6MTcwNDk2OTkyMSwicGF0aCI6Ii8xMzkxMDk1MDIvMjk1ODgyMTAwLWYzZGQ3MzYyLTY0MGUtNGEwNS05MmYyLTU2NjI3ZGUwNzQwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxMDQ1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzA2NDk0NmM1N2EwMWJhZjY0YjgzNDg0MzM4NWQ2NjczZWEyMWM0OTFjZjU5MjRhMWQwNjBkNzEyODM3OThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pHHNFXJJl2AXLFK912QHd7PF77wp7w7Vli1eG9sWXmU)

![image](https://github.com/netease-youdao/QAnything/assets/141105427/466af6b6-2a88-4826-9efe-96e5fc154089)

Take a look at the error message here. It is probably because you have set up multiple card booting. Currently, our tritonserver does not support setting up multiple cards. Just change it to single card and it will be fine.：CUDA_VISIBLE_DEVICES=0

**Comment by maozixi1** [comment]
ok thanks
